kind: Pod
apiVersion: v1
metadata:
  name: super-pod
spec:
  containers:
    - name: rfam-cloud
      image: ikalvari/rfam-cloud:kubes
      command: ["cmsearch"]
      args: ["-h", ">", "/workdir/cmsearch_help.out"]
      volumeMounts:
      - mountPath: "/workdir"
        name: testglustfsclaim 
  volumes:
    - name: testglustfsclaim
      persistentVolumeClaim:
        claimName: firstclaim
      persistentVolumeReclaimPolicy: Retain
