kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: firstclaim
spec:
  storageClassName: gluster-heketi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
