apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: rfam-pod-pvc
 annotations:
  volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
#persistentVolumeReclaimPolicy: Retain
