apiVersion: v1
kind: Pod
metadata:
  name: rfam-pod
  labels:
    app: rfam-builder
spec:
  containers:
  - name: rfam-pod
    image: ikalvari/rfam-cloud:latest
    ports:
    - containerPort: 9876
    volumeMounts:
    - name: rfam-pod-storage # this one must match the volume name of the pvc
      mountPath: /workdir
  volumes:
  - name: rfam-pod-storage
    persistentVolumeClaim:
      claimName: rfam-pod-pvc # this one must match the pvc name
  restartPolicy: Always
