apiVersion: v1
kind: Pod
metadata:
  name: rfam-centos-user-pod
  labels:
    app: rfam-builder
spec:
  containers:
  - name: rfam-centos-user-pod
    image: ikalvari/rfam-cloud:user-test
    stdin: true 
    tty: true 
    ports:
    - containerPort: 9876
    volumeMounts:
    - name: rfam-user-pvc # this one must match the volume name of the pvc
      mountPath: /home/centos
  volumes:
  - name: rfam-user-pvc
    persistentVolumeClaim:
      claimName: rfam-user-pvc # this one must match the pvc name
  restartPolicy: Always
